run:
	diambra -r "D:\Research\Gaming_with_LLM\.diambra\roms" run -l python script.py

demo:
	diambra -r "D:\Research\Gaming_with_LLM\.diambra\roms" run -l python demo.py && python3 result.py

local:
	diambra -r "D:\Research\Gaming_with_LLM\.diambra\roms" run -l python local.py

install:
	pip3 install -r requirements.txt

go:
	while true; do make run; done